
services:
  elasticsearch:
    image: elasticsearch:9.3.3
    container_name: showdan-elastic
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
      - cluster.routing.allocation.disk.threshold_enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    restart: unless-stopped

  es-init:
    image: curlimages/curl:latest # Легковесный образ только с curl
    container_name: showdan-es-init
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    volumes:
      - ./init-es.sh:/scripts/init-es.sh:ro
      - ./es_performers_mapping.json:/scripts/es_performers_mapping.json:ro
      - ./performers_seed.ndjson:/scripts/performers_seed.ndjson:ro
    working_dir: /scripts
    # Скрипт сам дождется запуска ES благодаря циклу until curl в коде
    command: [ "sh", "./init-es.sh" ]

  db:
    image: kartoza/postgis
    container_name: "sql_db"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "showdan"
      POSTGRES_PASS: "XkVMBg5Ik7vEW1hq8Orb"
      POSTGRES_DB: "postgres"
    volumes:
      - db_data:/opt/postgres/data
      - ./init-script.sql:/docker-entrypoint-initdb.d/setup-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U showdan -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 20

  redis:
    image: redis:7-alpine
    container_name: showdan-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      elasticsearch:
        condition: service_started
      es-init:
        condition: service_started
      redis:
        condition: service_started
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://showdan:XkVMBg5Ik7vEW1hq8Orb@db:5432/postgres"
      REDIS_URL: "redis://redis:6379/0"
    image: showdan/backend
    container_name: "showdan_backend"
    ports:
      - "8000:8000"

volumes:
  elassandra_data:
    driver: local
  elassandra_logs:
    driver: local
  db_data:
    driver: local
  esdata:
    driver: local
  redis_data:
    driver: local
